name: Mirror "master" and "main" branches
on:
  push:
    branches:
      - master
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to "master"
        uses: zofrex/mirror-branch@v1
        with:
          target-branch: master
          force: false
      - name: Mirror to "main"
        uses: zofrex/mirror-branch@v1
        with:
          target-branch: main
          force: false
